Repository exercism/sqlite, pull requests merged in 2024-01, with the labels that each got.

#3 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny

#11 ci: add exercise testing ci
  .github/workflows/test.yml
  bin/verify-exercise-example
  bin/verify-exercises
Labels: x:type/ci, x:rep/large, x:type/coding

#14 docs: add general about doc
  docs/ABOUT.md
Labels: x:type/docs
